name: Maestro Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up java17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Grant permissions to emulator
        run: adb shell appops set run com.android.commands.settings android.permission.CAMERA allow     

      - name: Set up Android emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          target: default
          arch: x86
          profile: Nexus 6

      - name: Install Maestro
        run: |
          curl -sS https://get.maestro.io | bash
          export PATH=$HOME/.maestro/bin:$PATH

      - name: Run Maestro test
        run: maestro test /tests/*.yaml
