name: Maestro Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up java17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v3

      - name: Setup gradle build
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: current
          gradle-home-cache-cleanup: true
          #add-job-summary-pr-comment: on-failure

      - name: Setup android
        uses: android-actions/setup-android@v3
          
      - name: Set up Android emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          target: default
          arch: x86
          profile: Nexus 6
          script: ./gradlew connectedCheck --stacktrace

      - name: Install Maestro
        run: |
          curl -sS https://get.maestro.io | bash
          export PATH=$HOME/.maestro/bin:$PATH

      - name: Run Maestro test
        run: maestro test /tests/*.yaml
